New PR for pipeline mob session to main
adobe/asset-compute-sdk pull request #135
Opened 2021-07-22 20:01 UTC by pheenomenon

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes # (issue)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-07-22 20:17 UTC, pheenomenon commented on package.json
> +    "@nui/asset-compute-pipeline": "^0.1.4",
Once asset-compute-pipeline is open sourced sdk will need updates in package.json.

2021-07-22 20:17 UTC, pheenomenon commented on package.json
> +  "version": "0.0.1-pipeline-alpha",
Once asset-compute-pipeline is open sourced sdk will need updates in package.json.

2021-07-22 21:42 UTC, tmathern requested changes

2021-07-22 21:42 UTC, tmathern commented on lib/api.js
> +    console.log("worker(renditionCallback, options={})");
You can remove this log.

2021-07-22 21:42 UTC, tmathern commented on test-worker/worker.js
> +    console.log("In test-worker rendition callback", rendition)
I think you can remove that log line too.

2021-07-22 21:42 UTC, tmathern commented on test/api.test.js
> +        it.skip('pipeline: should not return transformers if no manifest file found', async () => {
Why keep the test if it's skipped?

2021-07-28 21:48 UTC, tmathern approved these changes

2021-07-28 22:03 UTC, jdelbick approved these changes

2021-07-28 23:45 UTC, merged